name: Second Workflow

# This GitHub Actions workflow is triggered by the completion of another workflow.
# The 'on' key specifies the event that will trigger the workflow.
# The 'workflow_run' event is used to trigger this workflow when another workflow completes.
# The 'workflows' key lists the names of the workflows that can trigger this workflow.
# In this case, the workflow named "Echo Job" will trigger this workflow upon its completion.
# The 'types' key specifies the types of activity that will trigger the workflow.
# Here, the workflow will be triggered when the "Echo Job" workflow has completed.
on:
  workflow_run:
    workflows: ["Echo Job"]
    types:
    #  - completed  # Trigger when the workflow has completed, regardless of the outcome (success, failure, or cancelled)
       - success    # Trigger only when the workflow has completed successfully
    #  - failure    # Trigger only when the workflow has failed
    #  - cancelled  # Trigger only when the workflow has been cancelled

jobs:
  dependent-job:
    runs-on: ubuntu-latest

   # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run dependent script
      run: echo "This runs after the first workflow succeeds!"